export default {
  PICKER_ACTION_OPEN: 'OPEN',
  PICKER_ACTION_SELECT: 'SELECT',
  PICKER_ACTION_CANCEL: 'CANCEL',
  TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
  SET_IS_ERROR: 'SET_IS_ERROR',
  SET_BANNERS_LIST: 'SET_BANNERS_LIST',
  SET_UPDATE_BANNERS_LIST: 'SET_UPDATE_BANNERS_LIST',
  SET_BANNER_DELETE: 'SET_BANNER_DELETE',
  SET_PRODUCT_BANNER: 'SET_PRODUCT_BANNER',
  SET_UPDATE_BANNER: 'SET_UPDATE_BANNER',
};
